# This is a simple YAML configuration file for a user profile

---
- hosts: localhost
  connection: local
  tasks:
    - name: example task
      debug:
        msg: "Hello world"

# Data types shown: string, boolean, list of strings
